import { createContext, useContext, useState } from "react";

const LanguageContext = createContext();

const translations = {
  tr: {
    dashboard: "Yönetim Merkezi",
    employees: "Çalışanlar",
    customers: "Müşteriler",
    corporate: "Kurumsal",
    authorization: "Yetkilendirme",
    my_workspace: "Yönetim Merkezi",
    support_center: "Destek Merkezi",
    hr: "İnsan Kaynakları",
    hr_tanim: "Tanım",
    hr_islem: "İşlem",
    insan_kaynaklari: "İnsan Kaynakları",
    pdks_vardiya: "Pdks Yönetimi",
    pdks_tanim: "Tanım",
    pdks_islem: "İşlem",
    pdks_rapor: "Rapor",
    ik_grp_tanim: "Tanım",
    ik_grp_islem: "İşlem",
    ik_grp_rapor: "Rapor",
    maas_bordro: "Maaş Bordro Yönetimi",
    maas_bordro_tanim: "Tanım",
    maas_bordro_islem: "İşlem",
    maas_bordro_rapor: "Rapor",
    devriye_yonetimi: "Devriye Yönetimi",
    devriye_tanim: "Tanım",
    devriye_islem: "İşlem",
    devriye_rapor: "Rapor",
    devriye_lokasyon: "Lokasyon & Checkpoint",
    devriye_vardiya_tanim: "Vardiya Tanımları",
    devriye_atama: "Vardiya & Devriye Planı",
    devriye_personel: "Güvenlik Personeli",
    devriye_qr_saha: "QR Devriye (Saha)",
    devriye_okuma_rapor: "Devriye Raporları",
    devriye_saat_rapor: "Olması Gereken Saatler Raporu",
    devriye_qr_yazdir: "QR Yazdır & Test Merkezi",
    ik_tanimlar: "Genel Tanımlar",
    is_takibi: "İş Takip Yönetimi",
    musteriler_menu: "Müşteri Yönetimi",
    is_takibi_dashboard: "Dashboard",
    musteri_panosu: "Müşteri Panosu",
    is_takibi_projeler: "Projeler",
    is_takibi_biletler: "Biletler",
    is_takibi_kanban: "Panolar",
    is_takibi_tanim: "Tanım",
    is_takibi_bilet_durumlari: "Bilet Durumları",
    is_takibi_bilet_tipleri: "Bilet Tipleri",
    is_takibi_islem: "İşlem",
    is_takibi_rapor: "Rapor",
    tools: "Araçlar",
    messages: "Mesajlar",
    personal_calendar: "Kişisel Takvim",
    todos: "Yapılacaklar",
    leave_requests: "İzin Talepleri",
    my_leave_requests: "İzinler",
    ik_leave_management: "İzin Yönetimi",
    ik_leave_requests: "İzin Yönetimi",
    ik_expense_requests: "Harcama Yönetimi",
    profile: "Profil",
    general_report: "Detaylı Performans",
    employee_report: "Çalışan Raporu",
    pdks: "PDKS",
    personel_hareketleri: "Kart Geçiş Geçmişi",
    pdks_kart_yonetimi: "Kart Yönetimi",
    org_chart: "Organizasyon Şeması",
    quick_report: "Hızlı Raporlama",
    system_admin: "Sistem Yönetimi",
    users: "Kullanıcılar",
    role_permissions: "Yetkilendirme",
    definitions: "Tanım Ekranları",
    cop_kutusu: "Çöp Kutusu",
    musteri_kullanicilari: "Müşteri Kullanıcıları",
    denetim_kaydi: "Denetim Kaydı",
    oturum_yonetimi: "Oturum Yönetimi",
    announcements: "Duyurular",
    leave_allowances: "İzin Hakları Yönetimi",
    leave_types: "İzin Türleri ve Kurallar",
    hakedisler: "Hakediş",
    sozlesme_yonetimi: "Sözleşme Yönetimi",
    sozlesme_tanim: "Tanım",
    sozlesme_islem: "İşlem",
    sozlesme_turleri: "Sözleşme Türleri",
    sozlesme_urunler: "Ürünler",
    sozlesme_moduller: "Modüller",
    sozlesmeler: "Sözleşmeler",
    expenses: "Harcamalar",
    stok_yonetimi: "Stok / Depo Yönetimi",
    stok_tanim: "Tanım",
    stok_islem: "İşlem",
    stok_rapor: "Rapor",
    stok_dashboard: "Kontrol Merkezi",
    stok_mobil: "Mobil Hızlı İşlem",
    stok_etiket: "Toplu QR/Barkod Yazdırma",
    stok_demirbas_sorgula: "Demirbaş Sorgula",
    stok_excel: "Excel Stok Yükleme",
    stok_urunler: "Malzeme Tanımı",
    stok_gruplar: "Ürün Grupları",
    stok_depolar: "Depolar",
    stok_raflar: "Raf Tanımları",
    stok_urun_raf: "Ürün - Raf Atama",
    stok_sahalar: "Sahalar / Projeler",
    stok_tedarikciler: "Tedarikçiler",
    stok_giris: "Stok Giriş",
    stok_cikis: "Stok Çıkış",
    stok_transfer: "Depo Transfer",
    stok_iade: "Tedarikçiye İade",
    stok_fisler: "Stok Fiş Listesi",
    stok_sayim: "Sayım / Envanter",
    stok_parti_takibi: "Parti & Raf Ömrü",
    stok_raporlar: "Stok Raporları",
    stok_satinalma: "Fiyat Analiz",
    stok_zimmet: "Zimmet",
    stok_zimmet_yerleri: "Zimmet Yeri Tanımları",
    stok_qnb: "QNB e-Belge",
    ik_bordro: "İK / Özlük / Bordro",
    ik_bordro_tanim: "Tanımlar",
    ik_bordro_islem: "İşlemler",
    ik_bordro_rapor: "Raporlar",
    ikb_subeler: "Şubeler / Lokasyonlar",
    ikb_bolumler: "Bölümler",
    ikb_personel: "Bordro Personel İşlemleri",
    ikb_zam: "Özlük & Zam Uygula",
    ikb_ozluk_evrak: "Özlük Evrakları",
    ikb_vardiyalar: "Vardiya Tanımları",
    ikb_vardiya_atama: "Vardiya Transferi",
    ikb_vardiya_planlari: "Vardiya Planları",
    ikb_tatil_sihirbazi: "Tatil Sihirbazı",
    ikb_puantaj: "Puantaj Cetveli",
    ikb_puantaj_rapor: "Puantaj Raporları",
    ikb_mesai: "Mesai Onayları",
    ikb_hakedis_ayar: "Bordrolama Ayarları",
    ikb_bordro_yemek: "Bordro Yemek & Cumartesi",
    ikb_kesinti: "Kesinti Merkezi",
    ikb_ic_borc: "İçeriye Borçlar",
    ikb_personel_masraf: "Bordro Masraf Kesintisi",
    ikb_bordro: "Bordrolama",
    ikb_maas_ozet: "Maaş Özet & Hareket Raporu",
    ikb_ay_kapanis: "Ay Kapanışı",
    ikb_sirket: "Şirket Bilgileri",
    ikb_tutanak: "Tutanak & İhtarlar",
    ikb_ilan: "İlanlar",
    ikb_izin_evrak: "İzin & Rapor Evrakları",
  },
  en: {
    dashboard: "Dashboard",
    employees: "Employees",
    customers: "Customers",
    corporate: "Corporate",
    authorization: "Authorization",
    my_workspace: "Operations Center",
    support_center: "Support Center",
    hr: "Human Resources",
    hr_tanim: "Definitions",
    hr_islem: "Operations",
    insan_kaynaklari: "Human Resources",
    pdks_vardiya: "PDKS Management",
    pdks_tanim: "Definitions",
    pdks_islem: "Operations",
    pdks_rapor: "Reports",
    ik_grp_tanim: "Definitions",
    ik_grp_islem: "Operations",
    ik_grp_rapor: "Reports",
    maas_bordro: "Payroll Management",
    maas_bordro_tanim: "Definitions",
    maas_bordro_islem: "Operations",
    maas_bordro_rapor: "Reports",
    devriye_yonetimi: "Patrol Management",
    devriye_tanim: "Definitions",
    devriye_islem: "Operations",
    devriye_rapor: "Reports",
    devriye_lokasyon: "Location & Checkpoint",
    devriye_vardiya_tanim: "Shift Definitions",
    devriye_atama: "Shift & Patrol Plan",
    devriye_personel: "Security Staff",
    devriye_qr_saha: "QR Patrol (Field)",
    devriye_okuma_rapor: "Patrol Reports",
    devriye_saat_rapor: "Expected Times Report",
    devriye_qr_yazdir: "QR Print & Test Center",
    ik_tanimlar: "General Definitions",
    is_takibi: "Job Tracking Management",
    is_takibi_dashboard: "Dashboard",
    musteriler_menu: "Customer Management",
    musteri_panosu: "Customer Dashboard",
    is_takibi_projeler: "Projects",
    is_takibi_biletler: "Tickets",
    is_takibi_kanban: "Boards",
    is_takibi_tanim: "Definitions",
    is_takibi_bilet_durumlari: "Ticket Statuses",
    is_takibi_bilet_tipleri: "Ticket Types",
    is_takibi_islem: "Operations",
    is_takibi_rapor: "Reports",
    tools: "Tools",
    messages: "Messages",
    personal_calendar: "Personal Calendar",
    todos: "To-Dos",
    leave_requests: "Leave Requests",
    my_leave_requests: "My Leaves",
    ik_leave_management: "Leave Management",
    ik_leave_requests: "Leave Management",
    ik_expense_requests: "Expense Management",
    profile: "Profile",
    general_report: "General Report",
    employee_report: "Employee Report",
    pdks: "PDKS",
    personel_hareketleri: "Card Log History",
    pdks_kart_yonetimi: "Card Management",
    org_chart: "Org Chart",
    quick_report: "Quick Report",
    system_admin: "System Administration",
    users: "Users",
    role_permissions: "Permissions",
    definitions: "Definitions",
    cop_kutusu: "Trash Bin",
    musteri_kullanicilari: "Customer Users",
    denetim_kaydi: "Audit Log",
    oturum_yonetimi: "Session Management",
    announcements: "Announcements",
    leave_allowances: "Leave Allowances",
    leave_types: "Leave Types",
    hakedisler: "Progress Payments",
    sozlesme_yonetimi: "Contract Management",
    sozlesme_tanim: "Definitions",
    sozlesme_islem: "Operations",
    sozlesme_turleri: "Contract Types",
    sozlesme_urunler: "Products",
    sozlesme_moduller: "Modules",
    sozlesmeler: "Contracts",
    expenses: "Expenses",
    stok_yonetimi: "Inventory / Warehouse",
    stok_tanim: "Definitions",
    stok_islem: "Operations",
    stok_rapor: "Reports",
    stok_dashboard: "Control Center",
    stok_mobil: "Mobile Quick Ops",
    stok_etiket: "Bulk QR/Barcode Print",
    stok_demirbas_sorgula: "Asset Lookup",
    stok_excel: "Excel Import",
    stok_urunler: "Product Cards",
    stok_gruplar: "Product Groups",
    stok_depolar: "Warehouses",
    stok_raflar: "Shelves",
    stok_urun_raf: "Product - Shelf Assignment",
    stok_sahalar: "Sites / Projects",
    stok_tedarikciler: "Suppliers",
    stok_giris: "Stock In",
    stok_cikis: "Stock Out",
    stok_transfer: "Warehouse Transfer",
    stok_iade: "Supplier Return",
    stok_fisler: "Stock Vouchers",
    stok_sayim: "Stock Count",
    stok_parti_takibi: "Batch & Shelf Life",
    stok_raporlar: "Inventory Reports",
    stok_satinalma: "Price Analysis",
    stok_zimmet: "Assignment",
    stok_zimmet_yerleri: "Assignment Locations",
    stok_qnb: "QNB e-Document",
    ik_bordro: "HR / Personnel / Payroll",
    ik_bordro_tanim: "Definitions",
    ik_bordro_islem: "Operations",
    ik_bordro_rapor: "Reports",
    ikb_subeler: "Branches / Locations",
    ikb_bolumler: "Departments",
    ikb_personel: "Payroll Personnel Actions",
    ikb_zam: "Records & Raise",
    ikb_ozluk_evrak: "Personnel Documents",
    ikb_vardiyalar: "Shift Definitions",
    ikb_vardiya_atama: "Shift Transfer",
    ikb_vardiya_planlari: "Shift Plans",
    ikb_tatil_sihirbazi: "Holiday Wizard",
    ikb_puantaj: "Timesheet",
    ikb_puantaj_rapor: "Timesheet Reports",
    ikb_mesai: "Overtime Approvals",
    ikb_hakedis_ayar: "Payroll Settings",
    ikb_bordro_yemek: "Meal & Saturday Rules",
    ikb_kesinti: "Deductions Center",
    ikb_ic_borc: "Internal Debts",
    ikb_personel_masraf: "Payroll Expense Deduction",
    ikb_bordro: "Payroll",
    ikb_maas_ozet: "Payroll Summary & Activity",
    ikb_ay_kapanis: "Month Closing",
    ikb_sirket: "Company Info",
    ikb_tutanak: "Records & Warnings",
    ikb_ilan: "Postings",
    ikb_izin_evrak: "Leave & Report Documents",
  },
};

export function LanguageProvider({ children }) {
  // Dil seçici UI'sı kaldırıldı — uygulama yalnız Türkçe. `language`/
  // `setLanguage` context'te (başka tüketicisi kalmasa da imza bozulmasın
  // diye) duruyor ama artık hiçbir yerden değiştirilmiyor; eski bir
  // oturumdan kalan `localStorage.app_language=en` de artık okunmuyor.
  const [language] = useState("tr");

  const t = (key) => {
    return translations[language]?.[key] || translations.tr?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: () => {}, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
