import { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

const translations = {
  tr: {
    dashboard: "Yönetim Merkezi",
    employees: "Çalışanlar",
    customers: "Müşteriler",
    corporate: "Kurumsal",
    authorization: "Yetkilendirme",
    my_workspace: "Yönetim Merkezi",
    support_center: "Destek Merkezi",
    hr: "İnsan Kaynakları",
    hr_tanim: "Tanım",
    ik_tanimlar: "Çalışan Tanımları",
    all_activities: "Tüm Aktiviteler",
    activities: "Aktiviteler",
    add_activity: "Aktivite Ekle",
    work_tracking: "İş Takip",
    is_takibi: "İş Takibi",
    musteriler_menu: "Müşteriler",
    is_takibi_dashboard: "Dashboard",
    musteri_panosu: "Müşteri Panosu",
    is_takibi_projeler: "Projeler",
    is_takibi_biletler: "Biletler",
    is_takibi_kanban: "Panolar",
    is_takibi_tanimlar: "İş Takibi Tanımlar",
    tools: "Araçlar",
    messages: "Mesajlar",
    personal_calendar: "Kişisel Takvim",
    todos: "Yapılacaklar",
    leave_requests: "İzin Talepleri",
    my_leave_requests: "İzinler",
    ik_leave_management: "İzin Yönetimi",
    ik_leave_requests: "İzin Yönetimi",
    ik_expense_requests: "Harcama Yönetimi",
    profile: "Profil",
    reports: "Raporlar",
    general_report: "Detaylı Performans",
    employee_report: "Çalışan Raporu",
    pdks: "PDKS",
    personel_hareketleri: "Personel Hareketleri",
    pdks_kart_yonetimi: "Kart Yönetimi",
    org_chart: "Organizasyon Şeması",
    quick_report: "Hızlı Raporlama",
    satis: "Satış",
    satis_aktivite_ekle: "Satış Aktivitesi",
    satis_teklifleri: "Teklifler",
    satis_raporlari: "Satış Masası",
    satis_masasi: "Satış Masası",
    system_admin: "Sistem Yönetimi",
    users: "Kullanıcılar",
    role_permissions: "Yetkilendirme",
    app_version: "Uygulama Versiyonu",
    definitions: "Tanım Ekranları",
    cop_kutusu: "Çöp Kutusu",
    musteri_kullanicilari: "Müşteri Kullanıcıları",
    denetim_kaydi: "Denetim Kaydı",
    oturum_yonetimi: "Oturum Yönetimi",
    announcements: "Duyurular",
    leave_allowances: "İzin Hakları Yönetimi",
    leave_types: "İzin Türleri ve Kurallar",
    hakedisler: "Hakediş",
    sozlesme_yonetimi: "Sözleşme Yönetimi",
    sozlesmeler: "Sözleşmeler",
    expenses: "Harcamalar",
    stok_yonetimi: "Stok / Depo Yönetimi",
    stok_dashboard: "Kontrol Merkezi",
    stok_mobil: "Mobil Hızlı İşlem",
    stok_etiket: "Etiket Bas",
    stok_excel: "Excel Stok Yükleme",
    stok_urunler: "Ürün Kartları",
    stok_gruplar: "Ürün Grupları",
    stok_depolar: "Depolar",
    stok_raflar: "Raf Tanımları",
    stok_urun_raf: "Ürün - Raf Atama",
    stok_sahalar: "Sahalar / Projeler",
    stok_tedarikciler: "Tedarikçiler",
    stok_giris: "Stok Giriş",
    stok_cikis: "Stok Çıkış",
    stok_transfer: "Depo Transfer",
    stok_iade: "Tedarikçiye İade",
    stok_fisler: "Stok Fiş Listesi",
    stok_talep: "Malzeme Talebi",
    stok_rezervasyon: "Proje Rezervasyonu",
    stok_sayim: "Sayım / Envanter",
    stok_parti_takibi: "Parti & Raf Ömrü",
    stok_raporlar: "Stok Raporları",
    stok_satinalma: "Satın Alma",
    stok_zimmet: "El Aletleri & Zimmet",
    stok_qnb: "QNB e-Belge",
    stok_fiyat_arastir: "Fiyat Araştır",
  },
  en: {
    dashboard: "Dashboard",
    employees: "Employees",
    customers: "Customers",
    corporate: "Corporate",
    authorization: "Authorization",
    my_workspace: "Operations Center",
    support_center: "Support Center",
    hr: "Human Resources",
    hr_tanim: "Definitions",
    ik_tanimlar: "Employee Definitions",
    all_activities: "All Activities",
    activities: "Activities",
    add_activity: "Add Activity",
    work_tracking: "Work Tracking",
    is_takibi: "İş Takibi",
    is_takibi_dashboard: "Dashboard",
    musteri_panosu: "Customer Dashboard",
    is_takibi_projeler: "Projects",
    is_takibi_biletler: "Tickets",
    is_takibi_kanban: "Boards",
    is_takibi_tanimlar: "Job Tracking Definitions",
    tools: "Tools",
    messages: "Messages",
    personal_calendar: "Personal Calendar",
    todos: "To-Dos",
    leave_requests: "Leave Requests",
    my_leave_requests: "My Leaves",
    ik_leave_management: "Leave Management",
    ik_leave_requests: "Leave Management",
    ik_expense_requests: "Expense Management",
    profile: "Profile",
    reports: "Reports",
    general_report: "General Report",
    employee_report: "Employee Report",
    pdks: "PDKS",
    personel_hareketleri: "Personnel Movements",
    pdks_kart_yonetimi: "Card Management",
    org_chart: "Org Chart",
    quick_report: "Quick Report",
    system_admin: "System Administration",
    users: "Users",
    role_permissions: "Permissions",
    app_version: "App Version",
    definitions: "Definitions",
    cop_kutusu: "Trash Bin",
    musteri_kullanicilari: "Customer Users",
    denetim_kaydi: "Audit Log",
    oturum_yonetimi: "Session Management",
    announcements: "Announcements",
    leave_allowances: "Leave Allowances",
    leave_types: "Leave Types",
    hakedisler: "Progress Payments",
    sozlesme_yonetimi: "Contract Management",
    sozlesmeler: "Contracts",
    expenses: "Expenses",
    stok_yonetimi: "Inventory / Warehouse",
    stok_dashboard: "Control Center",
    stok_mobil: "Mobile Quick Ops",
    stok_etiket: "Label Print",
    stok_excel: "Excel Import",
    stok_urunler: "Product Cards",
    stok_gruplar: "Product Groups",
    stok_depolar: "Warehouses",
    stok_raflar: "Shelves",
    stok_urun_raf: "Product - Shelf Assignment",
    stok_sahalar: "Sites / Projects",
    stok_tedarikciler: "Suppliers",
    stok_giris: "Stock In",
    stok_cikis: "Stock Out",
    stok_transfer: "Warehouse Transfer",
    stok_iade: "Supplier Return",
    stok_fisler: "Stock Vouchers",
    stok_talep: "Material Request",
    stok_rezervasyon: "Project Reservation",
    stok_sayim: "Stock Count",
    stok_parti_takibi: "Batch & Shelf Life",
    stok_raporlar: "Inventory Reports",
    stok_satinalma: "Purchasing",
    stok_zimmet: "Tools & Assignment",
    stok_qnb: "QNB e-Document",
    stok_fiyat_arastir: "Price Research",
  },
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("app_language");
    return saved || "tr";
  });

  useEffect(() => {
    localStorage.setItem("app_language", language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.tr?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
